version: "2.3"
services:
  lcbot:
    cpus: 4
    mem_limit: "23g"
    working_dir: /lcbot
    image: eduherminio/lynx-docker
    build:
      context: .
      target: lcbot
    env_file:
      - .env
    volumes:
      - ./lcbot-config.yml:/lcbot/configtmp.yml
      - ./log:/lcbot/log
      - ./lynx-logs:/lynx/logs
    command:
      - sh
      - -c
      - |
        sed "s/LICHESS_API_TOKEN/$LICHESS_API_TOKEN/" configtmp.yml > config.yml
        . .venv/bin/activate
        python lichess-bot.py
